"""Missing, malformed and contradictory runtime evidence cannot pass."""
from dataclasses import replace
from pathlib import Path
import sys
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))
from lifecycle_boot_test import State, parse_state, check_state, permitted_intermediate


def fixture(step):
    # Independently listed settled observations, not generated by the validator.
    a = ((0, 0, 0, 0, 0, 0), (2, 1, 0, 0, 0, 0), (3, 1, 1, 1, 0, 0),
         (4, 1, 1, 1, 1, 0), *((5, 1, 1, 0, 1, 1),) * 5)[step]
    b = ((0, 0, 0, 0, 0, 0),) * 5 + ((2, 2, 0, 0, 0, 0), (4, 2, 1, 1, 1, 0),
                                     (5, 2, 1, 0, 1, 1), (5, 2, 1, 0, 1, 1))
    stats = ((0, 0, 0, 0, 0, 0, 0), (0, 0, 0, 0, 0, 0, 1), (0, 0, 0, 1, 0, 1, 1),
             (0, 0, 0, 1, 0, 1, 1), (0, 0, 0, 1, 1, 0, 1), (0, 0, 0, 1, 1, 0, 3),
             (0, 1, 2, 2, 1, 2, 3), (0, 1, 2, 2, 2, 0, 3), (0, 1, 2, 2, 2, 0, 3))
    fault = (0x200400, 0x0dead000, 0x92000046) if step >= 6 else (0, 0, 0)
    return State(step, (0, int(step >= 6), 0 if step == 0 else 1 if step < 5 else 2, *a, *b[step], *fault),
                 stats[step], (0 if step < 2 else 10000, 128 if step >= 6 else 0))


class LifecycleHarnessTests(unittest.TestCase):
    def test_valid_and_every_metadata_word_mutation(self):
        for step in range(9):
            state = fixture(step)
            line = b"STATE " + " ".join(map(str, (step, *state.supervisor, *state.broker, *state.counters))).encode()
            self.assertEqual(parse_state(line), state)
            check_state(state, step)
            for field in ("supervisor", "broker"):
                for i in range(len(getattr(state, field))):
                    with self.subTest(step=step, field=field, index=i):
                        words = list(getattr(state, field))
                        # Different translation-fault levels are valid; flip
                        # the required write direction for a syndrome negative.
                        words[i] ^= 64 if field == "supervisor" and i == 17 else 1
                        bad = replace(state, **{field: tuple(words)})
                        with self.assertRaises(RuntimeError):
                            check_state(bad, step)
            for counters in ((0, 999), (1, 999)):
                with self.assertRaises(RuntimeError): check_state(replace(state, counters=counters), step)

    def test_exact_unsigned_record_shape(self):
        base = b"STATE " + b" ".join([b"0"] * 28)
        for bad in (base + b" 0", base[:-2], base.replace(b"0", b"-1", 1), base + b"\n",
                    base.replace(b"0", b"00", 1), base.replace(b"0", b"18446744073709551616", 1),
                    base.replace(b"STATE", b"state"), base.replace(b" ", b"  ", 1)):
            with self.subTest(record=bad), self.assertRaises(RuntimeError): parse_state(bad)

    def test_wait_does_not_hide_fault_or_authority_errors(self):
        for step in (1, 2, 5, 6):
            state = fixture(step)
            words = list(state.supervisor)
            if step in (1, 5): words[3 if step == 1 else 9] = 1
            if step == 6:
                words[1] = 0; words[9:15] = (3, 2, 0, 0, 0, 0); words[15:] = (0, 0, 0)
                state = replace(state, broker=(0, 0, 0, 1, 1, 0, 3), counters=(10000, 0))
            partial = replace(state, supervisor=tuple(words))
            self.assertTrue(permitted_intermediate(partial, step))
            for field in (0, 1, 15, 16, 17):
                corrupt = list(partial.supervisor); corrupt[field] = 123
                self.assertFalse(permitted_intermediate(replace(partial, supervisor=tuple(corrupt)), step))
            self.assertFalse(permitted_intermediate(replace(partial, broker=(1, *partial.broker[1:])), step))
        self.assertFalse(permitted_intermediate(fixture(6), 6))


if __name__ == "__main__":
    unittest.main()
